"""Execute the ten paper workstreams offline with frozen inputs and full journals.

These are retrospective method-transfer experiments. This command neither
submits orders nor opens a future holdout nor changes production admission.
"""
from __future__ import annotations

import argparse
from collections import Counter
from dataclasses import asdict, replace
from datetime import datetime, timezone
from io import BytesIO
import json
import logging
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

import numpy as np
import pandas as pd

from analysis.execution_calibration import execution_sample_report
from analysis.factor_registry import default_proxy_definitions, freeze_factor_registry
from analysis.paper_label_execution import refine_barrier_labels
from analysis.paper_label_signals import chronological_label_targets, fixed_horizon_cost_labels
from analysis.paper_labels import BarrierConfig, LabelCosts
from analysis.paper_portfolio import PaperSpec, default_paper_specs, run_paper_replay
from analysis.paper_risk import StressSpec, stress_inventory_path, risk_diagnostics
from analysis.label_account_reconciliation import reconcile_candidate_account
from analysis.paper_study import WINDOWS, factor_attribution, factor_proxies, load_verified_inputs, write_json
from analysis.paper_validation import cscv_pbo, white_reality_check
from analysis.research_evidence import ResearchEvidenceRun, candidate_panel_evidence, sharpe_dependence_diagnostic
from backtest.plot_style import PALETTE, chart_style, money_axis, save_figure, style_axes
from core.data_versions import DataVersionStore
from core.events import EventCodec
from core.reproducibility import sha256_file
from scripts.run_revalidation60 import source_hashes


def freeze_inputs(manifest_path, observation_path, output, observed_at):
    """Validate original identity, then replay only the content-addressed copies."""
    _, identity = load_verified_inputs(Path(manifest_path))
    files = {entry["file"]: Path(entry["path"]) for entry in identity["symbols"].values()}
    files.update({"manifest.json": Path(manifest_path), "signal_observation.json": Path(observation_path)})
    store = DataVersionStore(output / "frozen_inputs")
    raw = store.freeze_files("paper-roadmap-inputs", files, observed_at=observed_at,
        source_refs={"manifest_sha256": identity["manifest_sha256"]},
        metadata={"historical_availability": "unknown", "observation_input": "frozen past P0 candidate cohort, not regenerated by current source"})
    frames, records = {}, []
    for symbol, entry in identity["symbols"].items():
        if raw["files"][entry["file"]]["sha256"] != entry["sha256"]:
            raise ValueError("source changed between validation and immutable capture")
        frame = pd.read_csv(BytesIO(store.read_file(raw["snapshot_id"], entry["file"])),
            index_col="timestamp", parse_dates=True, float_precision="round_trip")
        frame.index = pd.to_datetime(frame.index, utc=True)
        frames[symbol] = frame
        for at, row in frame.iterrows():
            records.append({"record_id": f"{symbol}:{at.isoformat()}", "revision_id": entry["sha256"],
                "event_time": at.isoformat(), "observed_at": observed_at, "available_at": None,
                "data": {"symbol": symbol, **{k: float(row[k]) for k in ("open", "high", "low", "close", "volume")}}})
    if raw["files"]["manifest.json"]["sha256"] != identity["manifest_sha256"]:
        raise ValueError("manifest changed during snapshot")
    temporal = store.create_snapshot("paper-roadmap-daily-records", records,
        source_refs={"raw_snapshot_id": raw["snapshot_id"]},
        metadata={"timestamp_meaning": "event_time is daily bar start; import observation is not historic publication"})
    pit_count = len(store.as_of(temporal["snapshot_id"], at=observed_at))
    observation = json.loads(store.read_file(raw["snapshot_id"], "signal_observation.json"))
    snapshots = {"raw": raw, "temporal": temporal, "input_identity": identity,
        "historically_available_rows": pit_count, "point_in_time_complete": False}
    write_json(output / "input_snapshots.json", snapshots)
    return frames, observation, snapshots, store


def load_fine_input(path, output, observed_at):
    """Optional local manifest: timeframe, symbols {symbol: {file,sha256}}.

    Every fine CSV must include an explicit available_at column. Known bar close
    alone is not accepted as proof of the external feed's availability.
    """
    if path is None:
        return {}, "1h", None
    path = Path(path).resolve()
    manifest_hash = sha256_file(path)
    manifest = json.loads(path.read_text(encoding="utf-8"))
    files = {"manifest.json": path}
    for symbol, entry in manifest["symbols"].items():
        source = (path.parent / entry["file"]).resolve()
        if not source.is_relative_to(path.parent) or source.name != entry["file"]:
            raise ValueError("fine manifest must use local leaf filenames")
        if source.name in files or sha256_file(source) != entry["sha256"]:
            raise ValueError("fine input identity mismatch")
        files[source.name] = source
    store = DataVersionStore(output / "frozen_fine_inputs")
    snapshot = store.freeze_files("paper-roadmap-fine-inputs", files, observed_at=observed_at)
    if snapshot["files"]["manifest.json"]["sha256"] != manifest_hash:
        raise ValueError("fine manifest changed during capture")
    frames = {}
    for symbol, entry in manifest["symbols"].items():
        if snapshot["files"][entry["file"]]["sha256"] != entry["sha256"]:
            raise ValueError("fine source changed during capture")
        frame = pd.read_csv(BytesIO(store.read_file(snapshot["snapshot_id"], entry["file"])),
            index_col="timestamp", parse_dates=True, float_precision="round_trip")
        if "available_at" not in frame or frame.available_at.isna().any():
            raise ValueError("fine evidence requires explicit complete available_at")
        frames[symbol] = frame
    return frames, manifest["timeframe"], snapshot


def validate_frozen_observations(frames, observations):
    """Fixed and barrier labels must use the same frozen candidate/price facts."""
    candidates = observations["candidates"]
    by_id = {c["candidate_id"]: c for c in candidates}
    if len(by_id) != len(candidates):
        raise ValueError("duplicate frozen candidate identity")
    seen, checked = set(), 0
    for label in observations["outcomes"]:
        if label.get("horizon_bars") != 5:
            continue
        cid = label["candidate_id"]
        if cid in seen or cid not in by_id:
            raise ValueError("fixed label must have one known candidate")
        seen.add(cid)
        candidate = by_id[cid]
        if any(label[k] != candidate[k] for k in ("symbol", "direction")):
            raise ValueError("label/candidate contract mismatch")
        if label.get("status") != "matured":
            continue
        signal = pd.Timestamp(candidate["timestamp"])
        available = pd.Timestamp(candidate["context"]["available_at"])
        entry, exit_, mature = [pd.Timestamp(label[k]) for k in ("entry_time", "exit_bar", "available_at")]
        if any(t.tzinfo is None for t in (signal, available, entry, exit_, mature)):
            raise ValueError("aware candidate/label times required")
        if not (signal < available <= entry <= exit_ < mature) or exit_ - entry != pd.Timedelta(days=4):
            raise ValueError("invalid fixed label horizon or availability")
        frame = frames[candidate["symbol"]]
        expected = pd.date_range(entry, exit_, freq="D")
        if not expected.isin(frame.index).all():
            raise ValueError("fixed label missing frozen bar")
        if not np.allclose([label["entry_reference"], label["exit_reference"]],
                [frame.loc[entry, "open"], frame.loc[exit_, "close"]], rtol=1e-12, atol=1e-12):
            raise ValueError("fixed label prices differ from frozen OHLCV")
        checked += 1
    if seen != set(by_id):
        raise ValueError("fixed horizon family is incomplete")
    return {"candidate_count": len(candidates), "mature_fixed_labels_price_checked": checked,
        "status": "consistent_frozen_prices", "point_in_time_provenance": "unknown"}


def build_jobs(specs, windows=WINDOWS):
    jobs = []
    for window, start, end in windows:
        for spec in specs:
            for cost in (1., 1.5):
                jobs.append({"id": f"{window}__{spec.name}__cost{cost:g}__10000",
                    "window": window, "start": start, "end": end, "spec": asdict(spec),
                    "cost_multiplier": cost, "capital": 10000., "purpose": "comparison"})
    for name in ("trend_60_cost_aware", "trend_60_optimizer_no_cost"):
        spec = next(s for s in specs if s.name == name)
        window, start, end = windows[-1]
        for capital in (100000., 1000000.):
            for cost in (1., 1.5):
                jobs.append({"id": f"{window}__{name}__cost{cost:g}__{capital:g}",
                    "window": window, "start": start, "end": end, "spec": asdict(spec),
                    "cost_multiplier": cost, "capital": capital, "purpose": "capacity"})
    if len({j["id"] for j in jobs}) != len(jobs):
        raise ValueError("duplicate registered job")
    return jobs


def save_run(output, job, result):
    if not result["accounting"]["ok"] or result["accounting"]["minimum_cash"] < -1e-7:
        raise ValueError("accounting or cash constraint failed")
    folder = output / "runs" / job["id"]
    folder.mkdir(parents=True, exist_ok=False)
    for key in ("equity", "fills", "decisions", "execution_audit", "financing"):
        result[key].to_csv(folder / (key + ".csv"), index=key == "equity", index_label="timestamp" if key == "equity" else None)
    risk = risk_diagnostics(result["equity"], result["returns"], initial_capital=job["capital"])
    for name, content in (("accounting", result["accounting"]), ("risk", risk), ("spec", result["spec"])):
        write_json(folder / (name + ".json"), content)
    summary = {**result["summary"], "job_id": job["id"], "window": job["window"], "purpose": job["purpose"],
        "accounting_ok": True, "commission": result["accounting"]["commission"],
        "slippage": result["accounting"]["slippage"], "holding_cost": result["accounting"]["holding_cost"],
        "mean_gross_weight": float(result["equity"].gross_weight.mean()),
        "realized_vol_annual": float(result["returns"].std(ddof=1) * np.sqrt(365)), "risk": risk}
    write_json(folder / "summary.json", summary)
    return summary


def statistical_diagnostics(output, returns):
    evidence = {}
    for window, _, _ in WINDOWS:
        panel = pd.DataFrame(returns[window])
        panel.to_csv(output / ("candidate_returns_" + window + ".csv"), index_label="timestamp")
        # Cash is a registered benchmark, outside the Sharpe candidate family
        # because its variance is structurally zero. Nothing is dropped by result.
        candidates = panel.drop(columns=["cash"])
        n = len(candidates) // 8 * 8
        evidence[window] = {"dsr": candidate_panel_evidence(dict(candidates.items()), registered_before_results=True),
            "pbo": cscv_pbo(candidates.iloc[:n], family_complete=False),
            "pbo_declared_tail_exclusion": len(candidates) - n,
            "dependence_sharpe": {name: {str(lag): sharpe_dependence_diagnostic(series, max_lag=lag)
                for lag in (5, 20, 60)} for name, series in candidates.items()},
            "reality_check": {benchmark: {str(block): white_reality_check(candidates, panel[benchmark],
                iterations=500, block_length=block, bootstrap="circular", family_complete=False)
                for block in (5, 20, 60)} for benchmark in ("cash", "equal_weight")}}
    write_json(output / "statistics.json", evidence)
    return evidence


@chart_style()
def make_plots(output, summaries):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    from matplotlib.ticker import PercentFormatter
    rows = pd.DataFrame([{k: v for k, v in row.items() if k != "risk"} for row in summaries])
    names = ["cash", "equal_weight", "inverse_vol", "trend_60", "trend_60_inverse_vol",
        "trend_60_inverse_variance", "trend_60_partial", "trend_60_no_trade", "trend_60_cost_aware",
        "trend_60_optimizer_no_cost", "label_fixed_ev", "label_barrier_ev"]
    fig, axes = plt.subplots(1, 3, figsize=(17, 7), sharey=True, layout="constrained")
    try:
        for ax, (window, _, _) in zip(axes, WINDOWS):
            selected = rows[(rows.window == window) & (rows.cost_multiplier == 1) & (rows.initial_capital == 10000)].set_index("name").reindex(names)
            bars = ax.barh(names, selected.net_return * 100, height=.62,
                color=[PALETTE["positive"] if x >= 0 else PALETTE["negative"] for x in selected.net_return])
            style_axes(ax, grid_axis="x")
            ax.xaxis.set_major_formatter(PercentFormatter(xmax=100, decimals=0))
            ax.axvline(0, color=PALETTE["muted"], linewidth=.8, zorder=2)
            for bar, value in zip(bars, selected.net_return * 100):
                if np.isfinite(value):
                    ax.annotate(f"{value:.1f}%", (value, bar.get_y() + bar.get_height() / 2),
                        xytext=(5 if value >= 0 else -5, 0), textcoords="offset points",
                        ha="left" if value >= 0 else "right", va="center", fontsize=8.5,
                        color=PALETTE["ink"])
            ax.margins(x=.25, y=.035)
            ax.set_title(window.replace("_", "–"))
            ax.set_xlabel("Net return · retrospective")
        axes[0].invert_yaxis()
        axes[0].tick_params(axis="y", labelsize=9)
        fig.suptitle("Net returns across frozen windows", x=.02, ha="left", fontsize=17, fontweight="semibold")
        fig.supxlabel("Same spot cash account, costs, universe and decision gross cap · realised risks differ",
                      fontsize=9, color=PALETTE["muted"])
        save_figure(fig, output / "net_returns.png")
    finally:
        plt.close(fig)
    fig, ax = plt.subplots(figsize=(10, 5.8), layout="constrained")
    try:
        window = WINDOWS[-1][0]
        colors = {"trend_60_cost_aware": PALETTE["blue"], "trend_60_optimizer_no_cost": PALETTE["purple"]}
        labels = {"trend_60_cost_aware": "Cost-aware allocator", "trend_60_optimizer_no_cost": "Optimizer without cost penalty"}
        for name in ("trend_60_cost_aware", "trend_60_optimizer_no_cost"):
            for cost in (1., 1.5):
                group = rows[(rows.window == window) & (rows.name == name) & (rows.cost_multiplier == cost)].sort_values("initial_capital")
                ax.plot(group.initial_capital, group.net_return * 100, marker="o" if cost == 1 else "s",
                    color=colors[name], linestyle="-" if cost == 1 else "--", linewidth=2.,
                    markersize=5, markeredgecolor=PALETTE["surface"], markeredgewidth=.8,
                    label=f"{labels[name]} · costs ×{cost:g}")
        ax.set_xscale("log")
        style_axes(ax, percent=True, percent_scale=100)
        money_axis(ax, axis="x")
        ax.margins(x=.06, y=.12)
        ax.set_xlabel("Initial capital (USDT) · log scale")
        ax.set_ylabel("Net return")
        ax.set_title("Capacity sensitivity", fontsize=16)
        ax.legend(loc="upper center", bbox_to_anchor=(.5, -.18), ncol=2, fontsize=8.5)
        fig.supxlabel("Assumed OHLCV impact · not venue-calibrated capacity", fontsize=9, color=PALETTE["muted"])
        save_figure(fig, output / "capacity.png")
    finally:
        plt.close(fig)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=ROOT / "data/binance/1d/_manifest.json")
    parser.add_argument("--observations", type=Path, default=ROOT / "reports/paper_applications_20261003_v3/signal_observation.json")
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--fine-manifest", type=Path)
    parser.add_argument("--execution-input", type=Path)
    args = parser.parse_args(argv)
    output = args.output.resolve()
    output.mkdir(parents=True, exist_ok=False)
    logging.basicConfig(level=logging.WARNING, force=True)
    for logger in ("core.broker.fill_service", "core.broker.matching"):
        logging.getLogger(logger).setLevel(logging.WARNING)
    observed_at = datetime.now(timezone.utc).isoformat()
    source_before = source_hashes()
    frames, observations, snapshots, store = freeze_inputs(args.manifest, args.observations, output, observed_at)
    fine, fine_timeframe, fine_snapshot = load_fine_input(args.fine_manifest, output, observed_at)
    observation_validation = validate_frozen_observations(frames, observations)
    write_json(output / "observation_validation.json", observation_validation)
    execution_input = {"events": [], "as_of": observed_at, "source": "live"}
    frozen_execution = None
    if args.execution_input:
        frozen_execution = store.freeze_files("paper-roadmap-execution", {"observations.json": args.execution_input}, observed_at=observed_at)
        execution_input = json.loads(store.read_file(frozen_execution["snapshot_id"], "observations.json"))
        execution_input["events"] = [EventCodec.decode(json.dumps(e)) if isinstance(e, dict) and "format" in e else e
            for e in execution_input.get("events", [])]
        write_json(output / "execution_input_snapshot.json", frozen_execution)
    execution = execution_sample_report(**execution_input)
    write_json(output / "execution_calibration.json", execution)
    specs = default_paper_specs()
    aware = next(s for s in specs if s.name == "trend_60_cost_aware")
    specs.append(replace(aware, name="trend_60_optimizer_no_cost", cost_penalty_scale=0.))
    specs += [PaperSpec(name=name, signal="cash", rebalance_every=1) for name in ("label_fixed_ev", "label_barrier_ev")]
    jobs = build_jobs(specs)
    costs = LabelCosts(commission_bps_per_side=10, slippage_bps_per_side=5, spread_bps_per_side=1)
    parameters = {"schema": "paper-roadmap/v1", "jobs": jobs, "windows": WINDOWS,
        "snapshots": snapshots, "fine_snapshot": fine_snapshot, "execution_snapshot": frozen_execution,
        "observation_validation": observation_validation, "label_costs": asdict(costs),
        "barriers": asdict(BarrierConfig()), "label_model": {"minimum_train": 30, "train_days": 365, "holding_bars": 5},
        "statistics": {"periods_per_year": 365, "block_lengths": [5, 20, 60], "iterations": 500,
            "pbo_groups": 8, "pbo_axis": "leading multiple of 8; excluded tail count reported", "cash": "benchmark outside Sharpe candidate family"},
        "scope": "fixed BTC/ETH retrospective method transfer; historical publication unknown; no independent holdout",
        "stress": asdict(StressSpec()), "hypothetical_depth_usdt_per_asset": 100000.,
        "inventory_stress_scope": "every account timestamp; finite liquidation at worst proportional-loss snapshot",
        "stress_liquidation_steps": 10, "stress_holding_cost_bps_per_step": 1.,
        "label_account_attribution": "opening candidate ID to authoritative FIFO lot shares and financing ledger",
        "factor_block_length": 20, "factor_iterations": 500,
        "promotions": [], "real_orders_authorized": False}
    registry = ResearchEvidenceRun(candidates=[j["id"] for j in jobs], parameters=parameters,
        data_map=frames, output=output / "evidence", source_hashes=source_before)
    write_json(output / "protocol.json", registry.snapshot()["registration"])
    factor_snapshot = freeze_factor_registry(output / "factor_registry", default_proxy_definitions(),
        observed_at=observed_at, code_refs={"source_hashes": source_before})
    write_json(output / "factor_registry.json", factor_snapshot)
    last_close = next(iter(frames.values())).index[-1] + pd.Timedelta(days=1)
    labels = refine_barrier_labels(frames, observations["candidates"], config=BarrierConfig(), costs=costs,
        as_of=last_close, fine_frames=fine, fine_timeframe=fine_timeframe)
    fixed = fixed_horizon_cost_labels(observations["outcomes"], costs=costs)
    write_json(output / "barrier_labels.json", labels)
    write_json(output / "fixed_labels.json", fixed)
    targets, label_reports, candidate_targets = {}, {}, {}
    label_sources = {"label_fixed_ev": fixed, "label_barrier_ev": labels["outcomes"]}
    for name, outcome in (("label_fixed_ev", fixed), ("label_barrier_ev", labels["outcomes"])):
        targets[name], label_reports[name] = chronological_label_targets(observations["candidates"], outcome,
            next(iter(frames.values())).index, list(frames))
        targets[name].to_csv(output / (name + "_targets.csv"), index_label="timestamp")
        write_json(output / (name + "_predictions.json"), label_reports[name])
        owners = pd.DataFrame(None, index=targets[name].index, columns=targets[name].columns, dtype=object)
        for row in label_reports[name]["target_attribution"]:
            owners.loc[pd.Timestamp(row["timestamp"]), row["symbol"]] = row["candidate_id"]
        candidate_targets[name] = owners
    print(f"REGISTERED {len(jobs)} jobs; {snapshots['temporal']['record_count']} unknown-availability rows frozen", flush=True)
    summaries, failures, stresses, attributions, label_accounts = [], [], {}, {}, {}
    returns = {name: {} for name, _, _ in WINDOWS}
    factors = factor_proxies(frames)
    factors.to_csv(output / "factor_proxies.csv", index_label="timestamp")
    for number, job in enumerate(jobs, 1):
        registry.record(candidate=job["id"], phase="replay", status="started")
        try:
            result = run_paper_replay(frames, PaperSpec(**job["spec"]), start=job["start"], end=job["end"],
                initial_capital=job["capital"], cost_multiplier=job["cost_multiplier"],
                target_overrides=targets.get(job["spec"]["name"]),
                candidate_targets=candidate_targets.get(job["spec"]["name"]))
            name = job["spec"]["name"]
            if name in label_sources:
                reconciliation = reconcile_candidate_account(label_sources[name],
                    result["decisions"].to_dict("records"), result["fills"].to_dict("records"),
                    result["financing"].to_dict("records"), initial_capital=job["capital"],
                    final_equity=float(result["equity"].equity.iloc[-1]),
                    final_marks={s: float(frame.loc[result["equity"].index[-1], "close"]) for s, frame in frames.items()},
                    financing_complete=True, financing_timing="after_fills", quote_currency="USDT")
                if not reconciliation["accounting"]["ok"]:
                    raise ValueError("candidate/FIFO/financing account reconciliation failed")
                label_accounts[job["id"]] = {key: reconciliation[key] for key in ("status", "coverage", "accounting", "financing_complete")}
            summary = save_run(output, job, result)
            if name in label_sources:
                write_json(output / "runs" / job["id"] / "label_account_reconciliation.json", reconciliation)
            if job["purpose"] == "comparison" and job["cost_multiplier"] == 1.:
                name = job["spec"]["name"]
                attribution = factor_attribution(result["returns"], factors, iterations=500, block_length=20)
                stress = stress_inventory_path(result["equity"], frames,
                    depth_notional={s: 100000. for s in frames}, spec=StressSpec(),
                    max_liquidation_steps=10, holding_cost_bps_per_step=1.)
                if not stress["summary"]["accounting_ok"]:
                    raise ValueError("full inventory stress path accounting failed")
                stresses[job["id"]] = stress["summary"]
                stress["path"].to_csv(output / "runs" / job["id"] / "inventory_stress_path.csv", index_label="timestamp")
                returns[job["window"]][name] = result["returns"]
                attributions[job["id"]] = attribution
            summaries.append(summary)
            registry.record(candidate=job["id"], phase="replay", status="completed", summary=summary)
            print(f"{number}/{len(jobs)} {job['id']} net={summary['net_return']:.4f} fills={summary['fill_count']} accounting=ok", flush=True)
        except Exception as exc:
            failures.append({"job_id": job["id"], "type": type(exc).__name__, "message": str(exc)})
            registry.record(candidate=job["id"], phase="replay", status="failed", error=failures[-1])
            print(f"{number}/{len(jobs)} FAILED {job['id']}: {exc}", flush=True)
        except BaseException as exc:
            registry.record(candidate=job["id"], phase="replay", status="interrupted", error_type=type(exc).__name__)
            raise
    pd.DataFrame([{k: v for k, v in row.items() if k != "risk"} for row in summaries]).to_csv(output / "comparison.csv", index=False)
    write_json(output / "factor_attribution.json", attributions)
    write_json(output / "joint_stress.json", stresses)
    write_json(output / "label_account_reconciliation.json", label_accounts)
    if not failures:
        statistical_diagnostics(output, returns)
        make_plots(output, summaries)
    else:
        write_json(output / "statistics.json", {"status": "invalid", "reason": "failed candidates retained; full family required", "failures": failures})
    source_after = source_hashes()
    identity_check = registry.verify_identity(frames)
    identity_check.update(source_unchanged=source_after == source_before,
        source_verification="full_local_tree_start_and_end", raw_snapshot_verified=bool(store.verify_snapshot(snapshots["raw"]["snapshot_id"])))
    identity_check["identity_changed"] = not identity_check["data_unchanged"] or not identity_check["source_unchanged"]
    acceptance = {"schema": "paper-roadmap-acceptance/v1", "registered_at": observed_at,
        "planned_runs": len(jobs), "completed_runs": len(summaries), "failures": failures,
        "all_accounting_ok": bool(summaries) and all(s["accounting_ok"] for s in summaries),
        "identity": identity_check, "point_in_time_complete": False,
        "historical_global_search_complete": False, "independent_holdout": False,
        "label_summary": labels["summary"], "label_decisions": {k: dict(Counter(p["decision"] for p in v["predictions"])) for k, v in label_reports.items()},
        "label_accounting": {"runs": len(label_accounts), "all_ok": all(r["accounting"]["ok"] for r in label_accounts.values())},
        "inventory_stress": {"runs": len(stresses), "timestamps": sum(r["observations"] for r in stresses.values()),
            "all_accounting_ok": all(r["accounting_ok"] for r in stresses.values())},
        "real_venue_calibration": execution["real_venue_calibration"], "promotions": [],
        "implementation_exercised": list(range(1, 11)),
        "status": "retrospective_experiments_completed" if not failures and not identity_check["identity_changed"] else "invalid_or_incomplete",
        "remaining_evidence": ["historical publication/revisions and tradable membership",
            "complete parent-consistent fine data for barrier first touch", "full-market capitalization factors",
            "independent live quotes, request receipts and fills across sufficient dates", "new untouched prospective holdout"],
        "artifact_hashes": {p.relative_to(output).as_posix(): sha256_file(p) for p in output.rglob("*") if p.is_file() and "frozen_inputs" not in p.parts}}
    write_json(output / "acceptance.json", acceptance)
    print(json.dumps({k: acceptance[k] for k in ("status", "planned_runs", "completed_runs", "all_accounting_ok", "real_venue_calibration", "promotions")}), flush=True)
    return 0 if acceptance["status"] == "retrospective_experiments_completed" else 1


if __name__ == "__main__":
    raise SystemExit(main())
